CREATE TABLE IF NOT EXISTS Food
(
	FoodID INT NOT NULL PRIMARY KEY,
	Category VARCHAR(40) NOT NULL,
	VegMenu BOOL NULL,
	ChildrenMenu BOOL NULL,
	Bar BOOL NULL,
	Cost INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Tour
(
	TourID INT NOT NULL PRIMARY KEY,
	Food INT NOT NULL,
	Hotel INT NOT NULL,
	Cost INT NOT NULL,
	DateBegin DATE NOT NULL,
	DateEnd DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS City
(
	CityID INT NOT NULL PRIMARY KEY,
	Name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Hotel
(
	HotelID INT NOT NULL PRIMARY KEY,
	City INT NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Type VARCHAR(30) NULL,
	Class INT NULL,
	SwimPool BOOL NULL,
	Cost INT NOT NULL
);

CREATE TABLE IF NOT EXISTS HC
(
	CityID INT NOT NULL,
	HotelID INT NOT NULL,
	Owner VARCHAR(30) NULL
);

\d
